name: Lint, Build and Test
on: push
jobs:
  lint-build-test:
    runs-on: ubutu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        needs: Install dependencies
        run: npm run lint
      - name: Build Project
        needs: Lint code
        run: npm run build
      - name: Run tests
        needs: Build Project
        run: npm test
